### PR TITLE
Simplify tox config, tests against 3.5-3.8

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by mvdbeek** [comment]
Hmm, those tool tests didn't actually run.

**Comment by mvdbeek** [comment]
Cool, that's working fine now.

**Comment by nsoranzo** [comment]
Thanks @mvdbeek!

**Comment by mvdbeek** [comment]
Sure. Could you prepare a new release ?

**Comment by nsoranzo** [comment]
> Sure. Could you prepare a new release?

@mvdbeek Done, 1.1.4 is available on PyPI. I've also automated the deployment on tag via Travis.

**Pull request merged**
